project:
  type: website
  output-dir: docs

website:
  title: "Estabilidad — Ing. Civil"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Trabajos Prácticos"
        menu:
          - text: "TP1 — Fuerzas Concurrentes"
            href: tp1/index.qmd
          - text: "TP2 — Fuerzas No Concurrentes"
            href: tp2/index.qmd
          - text: "TP3 — Aplicaciones"
            href: tp3/index.qmd
          - text: "TP4 — Fuerzas en el Espacio"
            href: tp4/index.qmd
  page-footer:
    center: "Cátedra Zangara / Ronconi · Ingeniería Civil 2026"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    lang: es